components:
  - name: DocumentStore
    type: InMemoryDocumentStore
  - name: Retriever
    params:
      document_store: DocumentStore
    type: TfidfRetriever
  - name: Reader
    params:
      # set model_name_or_path to reflect local model_path or HF model_name
      model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
      # here we have used a base-cpu image
      use_gpu: false
      # for airgapped image, we should load models from local
      local_files_only: true
    type: FARMReader
  - name: TextFileConverter
    type: TextConverter
  - name: FileTypeClassifier
    type: FileTypeClassifier
pipelines:
  - name: query
    nodes:
      - inputs: [Query]
        name: Retriever
      - inputs: [Retriever]
        name: Reader
  - name: indexing
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: PDFFileConverter
        inputs: [FileTypeClassifier.output_2]
      - name: Preprocessor
        inputs: [PDFFileConverter, TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
version: ignore
